// Release version consistency check.
//
// Canonical source: `package.json#version`. This verifies the version is
// consistent across the single source and every derived artifact:
//   - src/version.ts            (generated by scripts/gen-version.mjs)
//   - .claude-plugin/plugin.json
//   - .codex-plugin/plugin.json (base semver, ignoring "+<suffix>" build metadata)
//
// AC-12: --version / doctor --json / package.json / packed artifacts report the
// same version; this check fails the release when they diverge.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const readJson = (path) => JSON.parse(readFileSync(resolve(root, path), "utf8"));
const readText = (path) => readFileSync(resolve(root, path), "utf8");

const packageJson = readJson("package.json");
const claude = readJson("plugins/project-intelligence/.claude-plugin/plugin.json");
const codex = readJson("plugins/project-intelligence/.codex-plugin/plugin.json");

const version = packageJson.version;
if (!version || !/^\d+\.\d+\.\d+/.test(version)) {
  throw new Error(`Invalid package.json version: ${version}`);
}

// src/version.ts must carry the same version string.
const versionTs = readText("src/version.ts");
const tsMatch = versionTs.match(/VERSION\s*=\s*"([^"]+)"/);
if (!tsMatch) {
  throw new Error("Unable to find VERSION in src/version.ts");
}

const values = {
  "package.json": version,
  "src/version.ts": tsMatch[1],
  "claude-plugin": claude.version,
  "codex-plugin": codex.version.split("+")[0],
};

const unique = new Set(Object.values(values));
if (unique.size !== 1) {
  const detail = Object.entries(values)
    .map(([k, v]) => `${k}=${v}`)
    .join(", ");
  throw new Error(`Release versions differ: ${detail}`);
}

console.log(`Release metadata is consistent: ${version}`);
