#!/usr/bin/env node
// Single source of truth for the release version.
//
// `package.json#version` is the canonical version. This script propagates it to:
//   - src/version.ts        (TypeScript module consumed by the Node core)
//   - dist/version.js       (compiled runtime artifact; created if dist exists)
//   - plugins/.../.claude-plugin/plugin.json#version
//   - plugins/.../.codex-plugin/plugin.json#version  (preserves any "+..." suffix)
//
// Used by `npm run build` (build depends on gen-version) and `npm run gen-version`.
// AC-12: --version / doctor / package.json / packed artifacts report the same version.

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function readJson(rel) {
  return JSON.parse(readFileSync(resolve(ROOT, rel), "utf8"));
}
function writeJson(rel, obj) {
  writeFileSync(resolve(ROOT, rel), JSON.stringify(obj, null, 2) + "\n");
}
function readText(rel) {
  return readFileSync(resolve(ROOT, rel), "utf8");
}
function writeText(rel, text) {
  writeFileSync(resolve(ROOT, rel), text);
}

const pkg = readJson("package.json");
const version = pkg.version;
if (!version || !/^\d+\.\d+\.\d+/.test(version)) {
  throw new Error(`Invalid package.json version: ${version}`);
}

// 1. src/version.ts — TypeScript source module (the migrated core's version API).
const versionTs = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json#version.
// Do not edit by hand; run \`npm run gen-version\` after changing the version.
export const VERSION = ${JSON.stringify(version)} as const;
`;
writeText("src/version.ts", versionTs);

// 2. dist/version.js — runtime artifact, created only when dist/ already exists
//    (the real build emits it via tsc; this keeps gen-version runnable standalone).
const distDir = resolve(ROOT, "dist");
if (existsSync(distDir)) {
  const versionJs = `// AUTO-GENERATED by scripts/gen-version.mjs.\nexport const VERSION = ${JSON.stringify(version)};\n`;
  writeText("dist/version.js", versionJs);
}

// 3. Claude plugin manifest.
const claudePath = "plugins/project-intelligence/.claude-plugin/plugin.json";
const claude = readJson(claudePath);
claude.version = version;
writeJson(claudePath, claude);

// 4. Codex plugin manifest — preserve any existing "+<suffix>" build metadata,
//    only re-stamping the base semver when package.json#version changes.
const codexPath = "plugins/project-intelligence/.codex-plugin/plugin.json";
const codex = readJson(codexPath);
const currentCodex = String(codex.version || "");
const existingSuffix = currentCodex.includes("+")
  ? currentCodex.slice(currentCodex.indexOf("+"))
  : "";
codex.version = existingSuffix ? `${version}${existingSuffix}` : `${version}+codex`;
writeJson(codexPath, codex);

console.log(`Version synced to ${version} across package.json, src/version.ts, dist/version.js, and both plugin.json.`);
